version: "3.8"
services:
  dawn_app:
    container_name: "dawn_app"
    image: simplepan/dawn_dev
    tty: true
    #privileged must be true
    privileged: true
    volumes:
      #map host folder to container
      - /f/project/git_project/my_project/dawn:/home/DAWN/workspace:rw
