version: "3.8"
services:
    dawn_app:
      container_name: "dawn_app"
      image: dawn_dev
      tty: true
      network_mode: "host"
      volumes:
      #map host folder to container
        - /E/share/docker_dir/dawn_dev:/home/DAWN/workspace:rw
        - /E/share/:/home/DAWN/host_share:rw
