version: "3.8"
services:
    dawn_app:
      container_name: "dawn_app"
      image: simplepan/dawn_dev
      tty: true
      network_mode: "host"
      volumes:
      #map host folder to container
        - /home/bot/Documents/dorabot/code/my_project:/home/DAWN/host_share:rw
